/*
 * eeprom.h
 *
 *  Created on: 2021/10/19
 *      Author: staff
 */

#ifndef EEPROM_H_
#define EEPROM_H_

#define EEPROM_SPEC_BYTE_SIZE 256
#define EEPROM_SPEC_PAGE_SIZE 32
#define EEPROM_SPEC_PAGE_BYTE_SIZE 8
#define EEPROM_SLAVE_ADDRESS (uint8_t)0b10100000

#define EEPROM_BUFFER_SIZE 128

typedef enum EEPROM_PAGE_NUMBER{
	EEPROM_PAGE_NUMBER_MODE = 0,
	EEPROM_PAGE_NUMBER_DISPLAY = 1,
	EEPROM_PAGE_NUMBER_OUTPUT = 2,
	EEPROM_PAGE_NUMBER_COMMUNICATION = 3,
	EEPROM_PAGE_NUMBER_COMPARISON_OUTPUT1 = 5,
	EEPROM_PAGE_NUMBER_COMPARISON_OUTPUT2 = 8,
	EEPROM_PAGE_NUMBER_ZERO_ADJUSTMENT = 12,
	EEPROM_PAGE_NUMBER_INFORMATION = 16,
	EEPROM_PAGE_NUMBER_CORRECTION_VALUE = 22,
}EEPROM_PAGE_NUMBER;


typedef enum EEPROM_STATUS{
	EEPROM_OK,
	EEPROM_NG,
}EEPROM_STATUS;

#endif /* EEPROM_H_ */
